# Generated by Django 4.0.5 on 2022-06-29 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='attack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Голова'), ('2', 'Туловище'), ('3', 'Левая рука'), ('4', 'Правая рука'), ('5', 'Левая нога'), ('6', 'Правая нога')], max_length=40), size=3),
        ),
        migrations.AlterField(
            model_name='fight',
            name='defend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Голова'), ('2', 'Туловище'), ('3', 'Левая рука'), ('4', 'Правая рука'), ('5', 'Левая нога'), ('6', 'Правая нога')], max_length=40), size=3),
        ),
    ]
