# Generated by Django 4.0.5 on 2022-06-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0002_alter_fight_attack_alter_fight_defend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('num_round', models.IntegerField(primary_key=True, serialize=False)),
                ('first_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='fight.fight')),
                ('second_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='fight.fight')),
            ],
        ),
    ]
