# Generated by Django 4.0.5 on 2022-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_fight_finished_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='first_player_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='second_player_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='num_round',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
