# Generated by Django 4.0.5 on 2022-08-26 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_statistic_first_player_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='attack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('голова', 'голова'), ('туловище', 'туловище'), ('левая рука', 'левая рука'), ('правая рука', 'правая рука'), ('левая нога', 'левая нога'), ('правая нога', 'правая нога')], max_length=40), size=3),
        ),
        migrations.AlterField(
            model_name='fight',
            name='defend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('голова', 'голова'), ('туловище', 'туловище'), ('левая рука', 'левая рука'), ('правая рука', 'правая рука'), ('левая нога', 'левая нога'), ('правая нога', 'правая нога')], max_length=40), size=3),
        ),
    ]
